language: c

sudo: required

branches:
  only:
    - master
    - travis_ci_test

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    # - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install loadkit
  - luarocks build https://raw.githubusercontent.com/leafo/moonscript/master/moonscript-dev-1.rockspec
  - luarocks install https://raw.githubusercontent.com/Nymphium/luakatsu/master/luakatsu-4.0-0.rockspec # for opts_spec (*≧∀≦)
  - make test
  - sudo make install

script:
  moor -Linspect -e 'print (require"inspect") {"hello", "world"}'

