language: c

sudo: false

env:
  global:
    - LUAROCKS = 2.3.0
  matrix:
    - LUA = 5.1
    - LUA = 5.2
    - LUA = 5.3
    - LUA = luajit
    - LUA = luajit2.0
    - LUA = luajit2.1

branches:
  only:
    - master

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install loadkit
  - luarocks make

script: make test

