language: c

sudo: required

branches:
  only:
    - master
    - travis_ci_test

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    # - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install loadkit
  - luarocks install luakatsu # for opts_spec (*≧∀≦)
  - luarocks install moonscript
  - make install
  - make test

script:
  moor -Linspect -e 'print (require"inspect") {"hello", "world"}'

