language: c

sudo: required

branches:
  only:
    - master
    - travis_ci_test

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    # - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install moor_busted_rockspec-scm-1.rockspec
  - luarocks install https://raw.githubusercontent.com/leafo/moonscript/master/moonscript-dev-1.rockspec
  - make rockmake
  - make test

script:
  moor -e 'print (require"inspect") {"hello", "world"}'

