language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    # - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec
  - luarocks install loadkit
  - luarocks build https://raw.githubusercontent.com/leafo/moonscript/master/moonscript-dev-1.rockspec
  - luarocks remove alt-getopt --force
  - luarocks install https://raw.githubusercontent.com/Nymphium/alt-getopt/master/alt-getopt-0.7.0-1.rockspec
  - luarocks install https://raw.githubusercontent.com/Nymphium/luakatsu/master/luakatsu-4.0-0.rockspec # for opts_spec (*≧∀≦)

script: make travis-ci

